# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
before_install:
  - sudo apt-get install g++
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
os:
  - linux
julia:
  - release
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-base-dev
      - libatlas-dev
      - libopencv-dev
      - gcc-4.8
      - g++-4.8

notifications:
  email: false

# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/americast/MXReader.jl.git")'
  - source ~/.julia/v0.5/MXReader/test/setup.sh
  - julia -e ' Pkg.build("MXReader"); Pkg.test("MXReader"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("MXReader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MXReader")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
